dynfi: Add dynfi support to bsdinstall
This will skip some step unneeded for us in the install process like
user setup, hostname etc ...
And this will install the packages present on the memstick.

diff --git a/usr.sbin/bsdinstall/scripts/auto b/usr.sbin/bsdinstall/scripts/auto
--- a/usr.sbin/bsdinstall/scripts/auto
+++ b/usr.sbin/bsdinstall/scripts/auto
@@ -153,7 +153,9 @@ trap true SIGINT	# This section is optional
 [ -z "$BSDINSTALL_SKIP_KEYMAP" ] && bsdinstall keymap
 
 trap error SIGINT	# Catch cntrl-C here
-if [ -z "$BSDINSTALL_SKIP_HOSTNAME" ]; then bsdinstall hostname || error "Set hostname failed"; fi
+
+# DynFi Not needed
+#if [ -z "$BSDINSTALL_SKIP_HOSTNAME" ]; then bsdinstall hostname || error "Set hostname failed"; fi
 
 export DISTRIBUTIONS="${DISTRIBUTIONS:-base.txz kernel.txz}"
 if [ ${PKGBASE_INSTALL} -eq 0 && -f $BSDINSTALL_DISTDIR/MANIFEST]; then
@@ -187,12 +189,6 @@ if [ ${PKGBASE_INSTALL} -eq 0 ]; then
 	LOCAL_DISTRIBUTIONS=`echo $LOCAL_DISTRIBUTIONS`	# Trim white space
 	FETCH_DISTRIBUTIONS=`echo $FETCH_DISTRIBUTIONS`	# Trim white space
 
-<<<<<<< HEAD
-if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
-	dialog --backtitle "$OSNAME Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
-	bsdinstall netconfig || error
-	NETCONFIG_DONE=yes
-=======
 	if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
 		dialog --backtitle "FreeBSD Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
 		bsdinstall netconfig || error
@@ -207,7 +203,6 @@ if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
 		test $MIRROR_BUTTON -eq 0 || error "No mirror selected"
 		export BSDINSTALL_DISTSITE
 	fi
->>>>>>> 7600aab42048 (WIP: bsdinstall: pkgbase)
 fi
 
 rm -f $PATH_FSTAB
@@ -362,19 +357,9 @@ case "$PARTMODE" in
 	;;
 esac
 
-<<<<<<< HEAD
-[ -f /usr/libexec/bsdinstall/local.pre-fetch ] && f_dprintf "Running local.pre-fetch" && sh /usr/libexec/bsdinstall/local.pre-fetch "$BSDINSTALL_CHROOT"
-
-if [ -n "$FETCH_DISTRIBUTIONS" ]; then
-	exec 3>&1
-	export BSDINSTALL_DISTDIR=$(`dirname $0`/fetchmissingdists 2>&1 1>&3)
-	FETCH_RESULT=$?
-	exec 3>&-
-=======
 if [ ${PKGBASE_INSTALL} -eq 0 && ! -z "$FETCH_DISTRIBUTIONS" ]; then
 	ALL_DISTRIBUTIONS="$DISTRIBUTIONS"
 	WANT_DEBUG=
->>>>>>> 7600aab42048 (WIP: bsdinstall: pkgbase)
 
 	# Download to a directory in the new system as scratch space
 	BSDINSTALL_FETCHDEST="$BSDINSTALL_CHROOT/usr/freebsd-dist"
@@ -450,27 +435,30 @@ if [ ${PKGBASE_INSTALL} -eq 0 ]; then
 	bsdinstall distextract || error "Distribution extract failed"
 else
 	bsdinstall pkgbase || error "Failed to install pkgbase"
+	bsdinstall dynfi || error "Failed to install dynfi"
 fi
 
 # Set up boot loader
 bsdinstall bootconfig || error "Failed to configure bootloader"
 
-[ -f /usr/libexec/bsdinstall/local.pre-configure ] && f_dprintf "Running local.pre-configure" && sh /usr/libexec/bsdinstall/local.pre-configure "$BSDINSTALL_CHROOT"
-
-bsdinstall rootpass || error "Could not set root password"
+# DynFi Not needed
+#[ -f /usr/libexec/bsdinstall/local.pre-configure ] && f_dprintf "Running local.pre-configure" && sh /usr/libexec/bsdinstall/local.pre-configure "$BSDINSTALL_CHROOT"
+#bsdinstall rootpass || error "Could not set root password"
 
 trap true SIGINT	# This section is optional
 if [ "$NETCONFIG_DONE" != yes ]; then
-	bsdinstall netconfig	# Don't check for errors -- the user may cancel
+# DynFi Not needed
+#	bsdinstall netconfig	# Don't check for errors -- the user may cancel
 fi
 [ -z "$BSDINSTALL_SKIP_TIME" ] && bsdinstall time
-[ -z "$BSDINSTALL_SKIP_SERVICES" ] && bsdinstall services
-[ -z "$BSDINSTALL_SKIP_HARDENING" ] && bsdinstall hardening
+# DynFi Not needed
+#[ -z "$BSDINSTALL_SKIP_SERVICES" ] && bsdinstall services
+#[ -z "$BSDINSTALL_SKIP_HARDENING" ] && bsdinstall hardening
 
-[ -z "$BSDINSTALL_SKIP_USERS" ] && dialog --backtitle "$OSNAME Installer" \
-	--title "Add User Accounts" --yesno \
-    "Would you like to add users to the installed system now?" 0 0 && \
-    bsdinstall adduser
+#[ -z "$BSDINSTALL_SKIP_USERS" ] && dialog --backtitle "$OSNAME Installer" \
+#	--title "Add User Accounts" --yesno \
+#    "Would you like to add users to the installed system now?" 0 0 && \
+#    bsdinstall adduser
 
 finalconfig() {
 	exec 3>&1
@@ -525,7 +513,7 @@ finalconfig() {
 }
 
 # Allow user to change his mind
-[ -z "$BSDINSTALL_SKIP_FINALCONFIG" ] && finalconfig
+#[ -z "$BSDINSTALL_SKIP_FINALCONFIG" ] && finalconfig
 
 trap error SIGINT	# SIGINT is bad again
 bsdinstall config  || error "Failed to save config"
@@ -534,19 +522,20 @@ if [ ! -z "$BSDINSTALL_FETCHDEST" ]; then
 	rm -rf "$BSDINSTALL_FETCHDEST"
 fi
 
-[ -f /usr/libexec/bsdinstall/local.post-configure ] && f_dprintf "Running local.post-configure" && sh /usr/libexec/bsdinstall/local.post-configure "$BSDINSTALL_CHROOT"
-
-if [ -z "$BSDINSTALL_SKIP_MANUAL" ]; then
-	dialog --backtitle "$OSNAME Installer" --title "Manual Configuration" \
-		--default-button no --yesno \
-		"The installation is now finished. Before exiting the installer, would you like to open a shell in the new system to make any final manual modifications?" 0 0
-	if [ $? -eq 0 ]; then
-		clear
-		echo This shell is operating in a chroot in the new system. \
-		    When finished making configuration changes, type \"exit\".
-		chroot "$BSDINSTALL_CHROOT" /bin/sh 2>&1
-	fi
-fi
+# DynFi Not needed
+#[ -f /usr/libexec/bsdinstall/local.post-configure ] && f_dprintf "Running local.post-configure" && sh /usr/libexec/bsdinstall/local.post-configure "$BSDINSTALL_CHROOT"
+#
+#if [ -z "$BSDINSTALL_SKIP_MANUAL" ]; then
+#	dialog --backtitle "$OSNAME Installer" --title "Manual Configuration" \
+#		--default-button no --yesno \
+#		"The installation is now finished. Before exiting the installer, would you like to open a shell in the new system to make any final manual modifications?" 0 0
+#	if [ $? -eq 0 ]; then
+#		clear
+#		echo This shell is operating in a chroot in the new system. \
+#		    When finished making configuration changes, type \"exit\".
+#		chroot "$BSDINSTALL_CHROOT" /bin/sh 2>&1
+#	fi
+#fi
 
 bsdinstall entropy
 bsdinstall umount
