DynFi: Force UFS install for now
Signed-off-by: Emmanuel Vadot <manu@FreeBSD.org>

diff --git a/usr.sbin/bsdinstall/scripts/auto b/usr.sbin/bsdinstall/scripts/auto
--- a/usr.sbin/bsdinstall/scripts/auto
+++ b/usr.sbin/bsdinstall/scripts/auto
@@ -332,42 +332,46 @@ case $CURARCH in
 		;;
 esac
 
-exec 3>&1
+# Dynfi: Force UFS for now
+#exec 3>&1
 #PARTMODE=`echo $PMODES | xargs dialog --backtitle "$OSNAME Installer" \
-PARTMODE=`echo $PMODES | xargs dialog --backtitle "DynFi Installer" \
-	--title "Partitioning" \
-	--item-help \
-	--menu "How would you like to partition your disk?" \
-	0 0 0 2>&1 1>&3` || exit 1
-exec 3>&-
+#PARTMODE=`echo $PMODES | xargs dialog --backtitle "DynFi Installer" \
+#	--title "Partitioning" \
+#	--item-help \
+#       --menu "How would you like to partition your disk?" \
+#       0 0 0 2>&1 1>&3` || exit 1
+#exec 3>&-
 
-case "$PARTMODE" in
-"$msg_auto_zfs")	# ZFS
-	bsdinstall zfsboot || error "ZFS setup failed"
-	bsdinstall mount || error "Failed to mount filesystem"
-	;;
-"$msg_auto_ufs")	# Guided UFS
-	bsdinstall autopart || error "Partitioning error"
-	bsdinstall mount || error "Failed to mount filesystem"
-	;;
-"$msg_shell")		# Shell
-	clear
-	echo "Use this shell to set up partitions for the new system. When finished, mount the system at $BSDINSTALL_CHROOT and place an fstab file for the new system at $PATH_FSTAB. Then type 'exit'. You can also enter the partition editor at any time by entering 'bsdinstall partedit'."
-	sh 2>&1
-	;;
-"$msg_manual")		# Manual
-	if f_isset debugFile; then
-		# Give partedit the path to our logfile so it can append
-		BSDINSTALL_LOG="${debugFile#+}" bsdinstall partedit || error "Partitioning error"
-	else
-		bsdinstall partedit || error "Partitioning error"
-	fi
-	bsdinstall mount || error "Failed to mount filesystem"
-	;;
-*)
-	error "Unknown partitioning mode"
-	;;
-esac
+#case "$PARTMODE" in
+#"$msg_auto_zfs")	# ZFS
+#	bsdinstall zfsboot || error "ZFS setup failed"
+#	bsdinstall mount || error "Failed to mount filesystem"
+#	;;
+#"$msg_auto_ufs")	# Guided UFS
+#	bsdinstall autopart || error "Partitioning error"
+#	bsdinstall mount || error "Failed to mount filesystem"
+#	;;
+#"$msg_shell")		# Shell
+#	clear
+#	echo "Use this shell to set up partitions for the new system. When finished, mount the system at $BSDINSTALL_CHROOT and place an fstab file for the new system at $PATH_FSTAB. Then type 'exit'. You can also enter the partition editor at any time by entering 'bsdinstall partedit'."
+#	sh 2>&1
+#	;;
+#"$msg_manual")		# Manual
+#	if f_isset debugFile; then
+#		# Give partedit the path to our logfile so it can append
+#		BSDINSTALL_LOG="${debugFile#+}" bsdinstall partedit || error "Partitioning error"
+#	else
+#		bsdinstall partedit || error "Partitioning error"
+#	fi
+#	bsdinstall mount || error "Failed to mount filesystem"
+#	;;
+#*)
+#	error "Unknown partitioning mode"
+#	;;
+#esac
+# Force UFS
+bdinstall autopart || error "Partitioning error"
+bsdinstall mount || error "Failed to mount filesystem"
 
 if [ ${PKGBASE_INSTALL} -eq 0 && ! -z "$FETCH_DISTRIBUTIONS" ]; then
 	ALL_DISTRIBUTIONS="$DISTRIBUTIONS"
