DynFi: Fix typo (bdinstall->bsdinstall)
Signed-off-by: Emmanuel Vadot <manu@FreeBSD.org>

diff --git a/usr.sbin/bsdinstall/scripts/auto b/usr.sbin/bsdinstall/scripts/auto
--- a/usr.sbin/bsdinstall/scripts/auto
+++ b/usr.sbin/bsdinstall/scripts/auto
@@ -352,7 +352,7 @@ esac
 #	;;
 #esac
 # Force UFS
-bdinstall autopart || error "Partitioning error"
+bsdinstall autopart || error "Partitioning error"
 bsdinstall mount || error "Failed to mount filesystem"
 
 if [ ${PKGBASE_INSTALL} -eq 0 && ! -z "$FETCH_DISTRIBUTIONS" ]; then
